# -*- coding: utf-8 -*-
"""A/B TESTING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O97XBgXuwLW12glwhilyiRnqNRTUvPAz
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
from google.colab import files

files.upload()

!ls   # check name

df = pd.read_excel("ecommerce_orders_500.xlsx")  # change if name differs
df.head()

df.head()
df.shape
df.columns

df['Revenue'] = df['Quantity'] * df['Price']

import numpy as np

np.random.seed(42)
df['group'] = np.random.choice(['control', 'test'], size=len(df))

df['group'].value_counts()

control = df[df['group'] == 'control']
test = df[df['group'] == 'test']

control_mean = control['Revenue'].mean()
test_mean = test['Revenue'].mean()

print("Control mean revenue:", control_mean)
print("Test mean revenue:", test_mean)

from scipy import stats

t, p = stats.ttest_ind(control['Revenue'], test['Revenue'])

print("p-value:", p)

alpha = 0.05

if p < alpha:
    print("Significant difference → Test performs better")
else:
    print("No significant difference → Keep control")

import matplotlib.pyplot as plt

plt.bar(['Control','Test'], [control_mean, test_mean])
plt.ylabel("Average Revenue")
plt.title("A/B Revenue Comparison")
plt.show()

summary = pd.DataFrame({
    'Control Mean':[control_mean],
    'Test Mean':[test_mean],
    'p_value':[p]
})

summary.to_csv("ab_test_summary.csv", index=False)

with open("final_recommendation.txt","w") as f:
    if p < 0.05:
        f.write("Test group generated higher revenue. Recommend implementing test strategy.")
    else:
        f.write("No significant improvement. Continue current strategy.")



files.download("ab_test_summary.csv")