# -*- coding: utf-8 -*-
"""Customer Segmentation (RFM Analysis).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZM3FAxjgYGE7jgOiyz5PJjLEgTFjdzAq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_excel("customer_segmentation_small.xlsx")
df.head()

df.info()
df.isnull().sum()

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
df.head()

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)
snapshot_date

rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'nunique',
    'TotalPrice': 'sum'
})

rfm.columns = ['Recency', 'Frequency', 'Monetary']
rfm.head()

rfm['R_score'] = pd.qcut(rfm['Recency'], 3, labels=[3,2,1])
rfm['F_score'] = pd.qcut(rfm['Frequency'], 3, labels=[1,2,3])
rfm['M_score'] = pd.qcut(rfm['Monetary'], 3, labels=[1,2,3])

rfm['RFM_Score'] = (
    rfm['R_score'].astype(str) +
    rfm['F_score'].astype(str) +
    rfm['M_score'].astype(str)
)

rfm.head()

def segment(row):
    if row['R_score'] == 4 and row['F_score'] == 4:
        return 'Champions'
    elif row['F_score'] >= 3:
        return 'Loyal Customers'
    elif row['R_score'] == 1:
        return 'At Risk'
    else:
        return 'Others'

rfm['Segment'] = rfm.apply(segment, axis=1)

rfm

import matplotlib.pyplot as plt

rfm['Segment'].value_counts().plot(kind='bar')
plt.title("Customer Segments Distribution")
plt.xlabel("Segment")
plt.ylabel("Number of Customers")
plt.show()

rfm.to_csv("RFM_Result.csv")