# -*- coding: utf-8 -*-
"""DATA VISUALIZATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6C6bynJlckcDq8Com0aeUy5ZbO1F9f8
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
files.upload()

df = pd.read_csv("retail_sales_sample.csv")

import pandas as pd

df = pd.read_csv("retail_sales_sample.csv")

df.head()

df.info()
df.columns

df.head()
df.info()
df.columns
df.shape

import matplotlib.pyplot as plt

import pandas as pd
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.hist(df['Profit'], bins=20)
plt.title("Profit Distribution")
plt.xlabel("Profit")
plt.ylabel("Frequency")
plt.grid()
plt.show()

plt.figure(figsize=(6,4))
plt.scatter(df['Sales'], df['Profit'])
plt.title("Sales vs Profit")
plt.xlabel("Sales")
plt.ylabel("Profit")
plt.grid()
plt.show()

df.columns

top_products = df.groupby('Category')['Sales'].sum().sort_values(ascending=False).head(10)

import matplotlib.pyplot as plt

top_products = df.groupby('Category')['Sales'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(8,5))
top_products.plot(kind='bar')
plt.title("Top Categories by Sales")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.grid()
plt.show()