# -*- coding: utf-8 -*-
"""MINI ETL PIPELINE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162CF8OazFYspYkn-5J9ypoo8mLtmE_Wd
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("retail_sales_sample.csv")
df.head()

df.info()

df.isnull().sum()

df = df.drop_duplicates()
print("Duplicates removed ✅")

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

df['order_date'] = pd.to_datetime(df['order_date'])
df['sales'] = df['sales'].astype(float)
df['profit'] = df['profit'].astype(float)

df.info()

df['profit_margin'] = df['profit'] / df['sales']
df.head()

customers = df[['customer_id', 'region']].drop_duplicates()
customers.head()

orders = df[['order_id', 'order_date', 'customer_id', 'sales', 'profit', 'profit_margin']]
orders.head()

products = df[['product_id', 'category']].drop_duplicates()
products.head()

customers.to_csv("customers.csv", index=False)
orders.to_csv("orders.csv", index=False)
products.to_csv("products.csv", index=False)

print("Files saved successfully ✅")

print("Original rows:", len(df))
print("Customers rows:", len(customers))
print("Orders rows:", len(orders))
print("Products rows:", len(products))

df.to_csv("processed_data.csv", index=False)
print("processed_data.csv created successfully ✅")